name: Build and Release EXE

on:
  push:
    branches:
      - "main"           # main 分支 push 時執行
    tags:
      - "v*.*.*"         # 當推送 vX.Y.Z tag 時，執行並發佈 Release

permissions:
  contents: write        # 允許上傳 Release 資料

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: pip install pyinstaller

    - name: Convert Python script to EXE
      run: pyinstaller --onefile --noconsole --clean ScanFilesFolders.py
      shell: cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: built-exe
        path: dist/ScanFilesFolders.exe

  release:
    needs: build
    # 當 push 事件發生在 main 分支或 tag 時都進行發佈
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: built-exe
        path: dist

    - name: Create or Update GitHub Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref }}
        name: ${{ github.ref }}
        body: "Windows 最新版本自動發佈"
        draft: false
        prerelease: false

    - name: Upload Asset to Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/ScanFilesFolders.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
