name: Build and Release EXE

on:
  push:
    tags:
      - "v*.*.*"         # 僅在推送符合 vX.Y.Z 格式的 tag 時執行

permissions:
  contents: write        # 允許上傳 Release 資料

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: pip install pyinstaller

    - name: Convert Python script to EXE
      run: pyinstaller --onefile --noconsole --clean ScanFilesFolders.py
      shell: cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: built-exe
        path: dist/ScanFilesFolders.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: built-exe
        path: dist

    - name: Create or Update GitHub Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        body: "Windows 最新版本自動發佈"
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Asset to Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/ScanFilesFolders.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
